import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {Move,RotateCcw,X,EyeOff,Pause} from 'lucide-react';
import {clampPosition,type Position} from '../lib/playerPosition';
function saved(){try{return JSON.parse(localStorage.getItem('studyspace-video-layout')||'null')}catch{return null}}
export function FloatingPlayer({title,onClose,onPause,children}:{title:string;onClose:()=>void;onPause:()=>void;children:ReactNode}){
 const [hidden,setHidden]=useState(false);
 const [layout]=useState(saved);const [large,setLarge]=useState(layout?.large===true);const [position,setPosition]=useState<Position>(layout?.position||{x:window.innerWidth-380,y:80});const [dragging,setDragging]=useState(false);const box=useRef<HTMLElement>(null);const drag=useRef<{x:number;y:number;start:Position}|null>(null);
 function constrain(p:Position){const rect=box.current?.getBoundingClientRect();return clampPosition(p,rect?.width||360,rect?.height||330,window.innerWidth,window.innerHeight)}
 useLayoutEffect(()=>{const resize=()=>setPosition(p=>{const next=constrain(p);return next.x===p.x&&next.y===p.y?p:next});const observer=new ResizeObserver(resize);if(box.current)observer.observe(box.current);window.addEventListener('resize',resize);resize();return()=>{observer.disconnect();window.removeEventListener('resize',resize)}},[]);
 useEffect(()=>{try{localStorage.setItem('studyspace-video-layout',JSON.stringify({large,position}))}catch{/* Optional preference. */}},[large,position]);
 return createPortal(<><aside ref={box} className={`youtube-float ${large?'youtube-large':''} ${dragging?'is-dragging':''}`} style={{left:position.x,top:position.y,bottom:'auto',visibility:hidden?'hidden':'visible',pointerEvents:hidden?'none':undefined}} aria-hidden={hidden} aria-label="YouTube mini-player"><div className="youtube-player-head"><button className="icon-button youtube-drag" title="Drag to move; arrow keys also move" aria-label="Move YouTube player" onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,start:position};setDragging(true)}} onPointerMove={e=>{if(drag.current)setPosition(constrain({x:drag.current.start.x+e.clientX-drag.current.x,y:drag.current.start.y+e.clientY-drag.current.y}))}} onPointerUp={()=>{drag.current=null;setDragging(false)}} onPointerCancel={()=>{drag.current=null;setDragging(false)}} onLostPointerCapture={()=>{drag.current=null;setDragging(false)}} onKeyDown={e=>{const delta:Record<string,Position>={ArrowLeft:{x:-20,y:0},ArrowRight:{x:20,y:0},ArrowUp:{x:0,y:-20},ArrowDown:{x:0,y:20}};if(delta[e.key]){e.preventDefault();setPosition(p=>constrain({x:p.x+delta[e.key].x,y:p.y+delta[e.key].y}))}}}><Move size={18}/></button><strong title={title}>{title}</strong><button className="icon-button" aria-label="Hide player without stopping" title="Hide without stopping" onClick={()=>setHidden(true)}><EyeOff size={18}/></button><button className="icon-button" title="Stop and close" aria-label="Stop and close YouTube player" onClick={onClose}><X size={18}/></button></div><div className="youtube-layout-controls"><button onClick={()=>setLarge(v=>!v)}>{large?'Compact player':'Larger player'}</button><button aria-label="Reset player position" onClick={()=>setPosition(constrain({x:window.innerWidth-380,y:80}))}><RotateCcw size={14}/>Reset position</button></div>{children}</aside>{hidden&&<div className="youtube-hidden-controls" role="group" aria-label="Hidden YouTube player"><button onClick={()=>setHidden(false)} title={title}>♫ Show player</button><button aria-label="Pause hidden YouTube player" onClick={onPause}><Pause size={16}/></button><button aria-label="Stop and close YouTube player" onClick={onClose}><X size={16}/></button></div>}</>,document.body)
}

