import {useEffect,useRef,useState} from 'react';
import {ExternalLink,Search,X} from 'lucide-react';
import {request} from '../lib/api';
import {youtubeId} from '../lib/youtube';
type Video={id:string;title:string;channel?:string};
type Player={pauseVideo:()=>void;destroy:()=>void;cueVideoById:(id:string)=>void;getIframe:()=>HTMLIFrameElement};
type YouTube={Player:new(element:HTMLElement,options:{width:string;height:string;videoId:string;playerVars:Record<string,string|number>;events:{onReady:(event:{target:Player})=>void;onStateChange:(event:{data:number})=>void;onError:()=>void}})=>Player};
declare global {interface Window{YT?:YouTube;onYouTubeIframeAPIReady?:()=>void}}
let loader:Promise<YouTube>|undefined;
function loadYouTube():Promise<YouTube>{
 if(window.YT?.Player)return Promise.resolve(window.YT);
 if(loader)return loader;
 loader=new Promise((resolve,reject)=>{const script=document.createElement('script');const timeout=window.setTimeout(()=>{loader=undefined;script.remove();reject(new Error('YouTube player timed out. Try again or open on YouTube.'))},15000);window.onYouTubeIframeAPIReady=()=>{clearTimeout(timeout);resolve(window.YT!)};script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{clearTimeout(timeout);loader=undefined;script.remove();reject(new Error('YouTube could not load. Check your connection.'))};document.head.append(script)});return loader;
}
export function YouTubeMusic({active}:{active:boolean}){
 const [query,setQuery]=useState('');const [link,setLink]=useState('');const [results,setResults]=useState<Video[]>([]);const [selected,setSelected]=useState<Video>();const [error,setError]=useState('');const [playerError,setPlayerError]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);
 const mount=useRef<HTMLDivElement>(null);const player=useRef<Player|undefined>(undefined);
 const requestId=useRef(0);
 useEffect(()=>{if(!selected)return;let cancelled=false;setReady(false);setPlayerError('');const child=document.createElement('div');mount.current!.append(child);
 void loadYouTube().then(YT=>{if(cancelled)return;player.current=new YT.Player(child,{width:'100%',height:'220',videoId:selected.id,playerVars:{playsinline:1,origin:location.origin,autoplay:0},events:{onReady:({target})=>{target.getIframe().setAttribute('referrerpolicy','strict-origin-when-cross-origin');setReady(true)},onStateChange:({data})=>{if(data===1){if(document.hidden)player.current?.pauseVideo();else window.dispatchEvent(new Event('studyspace-youtube-playing'))}},onError:()=>setPlayerError('This video cannot play here. Try another result or open it on YouTube.')}})}).catch(e=>{if(!cancelled)setPlayerError(e.message)});
 const pause=()=>player.current?.pauseVideo();const visibility=()=>{if(document.hidden)pause()};window.addEventListener('studyspace-audio-playing',pause);document.addEventListener('visibilitychange',visibility);
 return()=>{cancelled=true;window.removeEventListener('studyspace-audio-playing',pause);document.removeEventListener('visibilitychange',visibility);player.current?.destroy();player.current=undefined;child.remove()};},[selected]);
 async function search(){const id=++requestId.current;setBusy(true);setError('');try{const items=await request<Video[]>(`/music/youtube/search?q=${encodeURIComponent(query.trim())}`);if(id===requestId.current){setResults(items);if(!items.length)setError('No embeddable videos found. Try another search.')}}catch(e){if(id===requestId.current)setError((e as Error).message)}finally{if(id===requestId.current)setBusy(false)}}
 return <><section hidden={!active} className="youtube-search-panel"><h3>YouTube music & study videos</h3><p className="view-footnote">The visible mini-player stays available while you navigate this workspace. Playback pauses when this browser tab is hidden. Some videos disable embedding.</p><form className="music-search" onSubmit={e=>{e.preventDefault();void search()}}><Search size={18}/><input aria-label="Search YouTube" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search songs, artists, or study mixes…"/><button className="button" disabled={busy||!query.trim()}>{busy?'Searching…':'Search YouTube'}</button></form><form className="music-search" onSubmit={e=>{e.preventDefault();const id=youtubeId(link);if(id){setSelected({id,title:'YouTube video'});setError('')}else setError('Paste a valid YouTube video link or video ID.')}}><input aria-label="YouTube video link" value={link} onChange={e=>setLink(e.target.value)} placeholder="Paste a YouTube link — no API key needed"/><button className="button" disabled={!link.trim()}>Open player</button></form><details><summary>Enable in-app YouTube search</summary><p className="view-footnote">Add YOUTUBE_API_KEY to your Docker .env file, enable YouTube Data API v3 for that key, then run docker compose up -d. Search uses your API quota. Link playback works without a key.</p></details>{error&&<p role="alert" className="form-error">{error}</p>}<div className="youtube-results">{results.map(video=><button className="panel youtube-result" key={video.id} onClick={()=>setSelected(video)}><span className="youtube-badge">▶ YouTube</span><strong>{video.title}</strong><small>{video.channel}</small><span>Open player →</span></button>)}</div></section>{selected&&<aside className="youtube-float" aria-label="YouTube mini-player"><div className="youtube-player-head"><strong>{selected.title}</strong><button className="icon-button" aria-label="Close YouTube player" onClick={()=>setSelected(undefined)}><X size={18}/></button></div><div ref={mount} className="youtube-embed"/>{!ready&&!playerError&&<p role="status">Loading YouTube…</p>}{playerError&&<p role="alert">{playerError}</p>}<a href={`https://www.youtube.com/watch?v=${selected.id}`} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Open on YouTube</a></aside>}</>;
}
