import { useEffect, useState } from 'react';
import { CalendarDays, MapPin, Plus, Video, Repeat2 } from 'lucide-react';
import { request } from '../lib/api';
import { Modal } from '../components/Modal';
export type Meeting = {id:number; title:string; start_local:string; timezone:string; duration:number; frequency:string; interval:number; count:number|null; until:string|null; place:string; link:string; notes:string; color:string};
export type Occurrence = Meeting & {starts_at:string; ends_at:string; occurrence_key:string};
const fresh = (): Omit<Meeting,'id'> => ({title:'', start_local:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,duration:60,frequency:'weekly',interval:1,count:null,until:null,place:'',link:'',notes:'',color:'#7dd3fc'});
export function MeetingForm({meeting,onClose,onSaved}:{meeting?:Meeting;onClose:()=>void;onSaved:()=>void}) {
 const [form,setForm]=useState(meeting || fresh());const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const set=(key:string,value:unknown)=>setForm(prev=>({...prev,[key]:value}));
 return <Modal title={meeting?'Edit meeting series':'New meeting'} onClose={onClose} wide><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const {id:_,...body}=form as Meeting;await request(meeting?`/meetings/${meeting.id}`:'/meetings',meeting?'PUT':'POST',body);onSaved();onClose();}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>
 <label>Meeting title<input required maxLength={200} value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Weekly project check-in"/></label>
 <div className="settings-grid"><label>First meeting<input required type="datetime-local" onInput={e=>set("start_local",e.currentTarget.value)} value={form.start_local.slice(0,16)} onChange={e=>set('start_local',e.target.value)}/></label><label>Duration (minutes)<input required type="number" min={5} max={1440} value={form.duration} onChange={e=>set('duration',Number(e.target.value))}/></label><label>Time zone<input required value={form.timezone} onChange={e=>set('timezone',e.target.value)} placeholder="Asia/Dubai"/></label><label>Repeat<select value={form.frequency} onChange={e=>set('frequency',e.target.value)}><option value="once">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label></div>
 {form.frequency!=='once'&&<div className="settings-grid"><label>Every N {form.frequency==='weekly'?'weeks (2 = fortnightly)':form.frequency==='daily'?'days':'months'}<input required type="number" min={1} max={52} value={form.interval} onChange={e=>set('interval',Number(e.target.value))}/></label><label>Ends<select value={form.count?'count':form.until?'until':'never'} onChange={e=>{set('count',e.target.value==='count'?10:null);set('until',e.target.value==='until'?form.start_local.slice(0,10):null)}}><option value="never">Never</option><option value="count">After N scheduled repeats</option><option value="until">On a date</option></select></label>{form.count!==null&&<label>Scheduled repeats (includes first)<input type="number" required min={1} max={1000} value={form.count} onChange={e=>set('count',Number(e.target.value))}/></label>}{form.until!==null&&<label>Last date (inclusive)<input type="date" onInput={e=>set("until",e.currentTarget.value)} required min={form.start_local.slice(0,10)} value={form.until} onChange={e=>set('until',e.target.value)}/></label>}</div>}
 <label>Place<input maxLength={300} value={form.place} onChange={e=>set('place',e.target.value)} placeholder="Room B204 or online"/></label><label>Meeting link<input type="url" value={form.link} onChange={e=>set('link',e.target.value)} placeholder="https://…"/></label><label>Agenda / notes<textarea rows={3} maxLength={10000} value={form.notes} onChange={e=>set('notes',e.target.value)}/></label><label>Calendar color<input type="color" value={form.color} onChange={e=>set('color',e.target.value)}/></label>
 <p className="view-footnote">Repeats keep the meeting’s local time across daylight-saving changes. Missing dates or clock-change times are skipped. Edits affect the whole series.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="button primary">{busy?'Saving…':'Save meeting'}</button></form></Modal>
}
export function MeetingsView(){const [items,setItems]=useState<Meeting[]>([]);const [edit,setEdit]=useState<Meeting|null|undefined>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);void request<Meeting[]>('/meetings').then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);
 return <div className="view-content"><div className="view-toolbar"><div><h2>Your meeting rhythm</h2><p className="view-footnote">One place for classes, check-ins, and weekly conversations.</p></div><button className="button primary" onClick={()=>setEdit(null)}><Plus size={18}/>New meeting</button></div>{error&&<p role="alert">{error}</p>}{loading&&<p>Loading meetings…</p>}<div className="meeting-grid">{items.map(m=><article className="meeting-card" key={m.id} style={{borderTopColor:m.color}}><span className="meeting-eyebrow"><Repeat2 size={16}/>{m.frequency==='once'?'One-time meeting':`Every ${m.interval} ${m.frequency==='weekly'?'week(s)':m.frequency==='daily'?'day(s)':'month(s)'}`}</span><h3>{m.title}</h3><p><CalendarDays size={16}/>{m.start_local.replace('T',' ').slice(0,16)} · {m.duration} min</p><small>{m.timezone}{m.count?` · ${m.count} scheduled repeats`:m.until?` · Until ${m.until}`:''}</small>{m.place&&<p><MapPin size={16}/>{m.place}</p>}{m.notes&&<p className="meeting-notes">{m.notes}</p>}<div className="meeting-actions">{m.link&&<a className="button" href={m.link} target="_blank" rel="noreferrer"><Video size={16}/>Join</a>}<button className="button" onClick={()=>setEdit(m)}>Edit series</button><button className="text-button" onClick={async()=>{if(confirm(`Delete all occurrences of “${m.title}”?`)){try{await request(`/meetings/${m.id}`,'DELETE');load()}catch(e){setError((e as Error).message)}}}}>Delete</button></div></article>)}</div>{!loading&&!items.length&&<div className="empty-state"><CalendarDays size={32}/><h3>Make room for your meetings</h3><p>Add your first meeting. Its occurrences will appear in Calendar.</p></div>}{edit!==undefined&&<MeetingForm meeting={edit||undefined} onClose={()=>setEdit(undefined)} onSaved={load}/>}</div>
}
